version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://35.234.119.103:9092

  kafka-connector:
    image: confluentinc/cp-kafka-connect:7.4.1
    ports:
      - 8083:8083
    links:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "35.234.119.103:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-kafka"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-kafka-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-kafka-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-kafka-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "35.234.119.103"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
    volumes:
      - $PWD/jars:/etc/kafka-connect/jars
volumes:
  kafka_data:
    driver: local